### PR TITLE
Spelling: Fourth instead of Forth

### PR DESCRIPTION
**Pull request by jdespatis**
http://www.grammar-monster.com/easily_confused/forth_fourth.htm

and fix links in svg file

### CODE REVIEW

**Comment by WouterJ** [comment]
Thank you @jdespatis. I like it very much that you even took the time to edit the svg files :)

**Comment by jdespatis** [comment]
I haven't touched the png though, but they're generated I guess?

**Comment by WouterJ** [comment]
I don't know how that works. Ping @dantleech do you know this?

**Comment by dantleech** [comment]
No they are not generated, you would need to re-export the png's

**Pull request merged**
