### PR TITLE
Removed invalid single quotes on version string

### PR DESCRIPTION
**Pull request by eiannone**

### CODE REVIEW

**Comment by WouterJ** [comment]
Thanks for submitting a fix, @eiannone! Can you please change them to double quotes, which are valid?

**Comment by eiannone** [comment]
Done, created another pull request https://github.com/symfony-cmf/symfony-cmf-docs/pull/678

**Comment by lsmith77** [comment]
just FYI .. you can push to the same branch on which the PR is based, it will just update the PR. so for example you could have just committed the adjustments vis ``git commit -a --amend; git push [your remote] [your branch]`` instead of creating a new PR.

**Comment by eiannone** [comment]
Thank you, I'm quite new to git, and didn't know how to do it.

**Pull request closed without merging**
