### PR TITLE
cleanup installation instructions

### PR DESCRIPTION
**Pull request by dbu**
we added create to the standard edition but missed to add the assetic:dump instructions.

fix https://github.com/symfony-cmf/CreateBundle/issues/134

### CODE REVIEW

**Comment by lsmith77** [comment]
we incrementally merge 1.2 into master .. right?

**Comment by WouterJ** [comment]
I would love to have an out of the box solution for this. This is just a case where I think "Hmm, that should be easier". It doesn't feel really DX perfect if you have to execute a command to use a shortcut.

**Comment by dbu** [comment]
well, if we go for the npm stack for assets, things will not get less complicated :-P (just saying...)

sofar we used assetic in most projects so i did not even notice this.

**Comment by dbu** [comment]
but that said, if you have an idea how to improve this, go for it. not sure if adding assetic to composer.json post-install makes a lot of sense though.

**Pull request merged**
