### PR TITLE
Fix route creation example

### PR DESCRIPTION
**Pull request by umeku**
| Q             | A
| ------------- | ---
| Doc fix?      | yes
| New docs?     | no
| Applies to    | all
| Fixed tickets | no

### CODE REVIEW

**Comment by lsmith77** [comment]
seems to only affect master

**Comment by WouterJ** [comment]
Also 1.2

**Comment by lsmith77** [comment]
ah .. there we did already branch of 1.2 ..

**Comment by lsmith77** [comment]
its a little confusing, since in the docs it looks like 1.2 and master are considered equivalent

**Comment by WouterJ** [comment]
Indeed, it looks like the version checker isn't updated yet (it's not done automatically).

@javiereguiluz can you maybe alias master to CMF 1.3?

**Comment by javiereguiluz** [comment]
@WouterJ done! But as always, we need to wait until the website is re-deployed.

**Pull request merged**
