### PR TITLE
Replaced the DI tag "cmf_menu.voter" to the right "knp_menu.voter"

### PR DESCRIPTION
**Pull request by hason**

### CODE REVIEW

**Comment by dbu** [comment]
@WouterJ do we need to add a `.. versionadded` tag here? menu bundle 1.0 had its own voter, but 2.0 uses the knp menu bundle

**Comment by dbu** [comment]
ping @WouterJ 

see also #726

**Comment by lsmith77** [comment]
can be merged?

**Comment by WouterJ** [comment]
I've included this commit in https://github.com/symfony-cmf/symfony-cmf-docs/pull/738

**Pull request closed without merging**
