### PR TITLE
Correct paths and fix comment

### PR DESCRIPTION
**Pull request by jdespatis**
SimpleCmsBundle is not installed in this part

### CODE REVIEW

**Comment by dbu** [comment]
indeed, thanks a lot!

**Comment by jdespatis** [comment]
you're welcome

Hope this doc will still be valid when 1.3, with its big roadmap, will be released!

**Comment by dbu** [comment]
1.3 will not break that much, only add features. the only thing that
probably really changes is sonata admin.

**Comment by jdespatis** [comment]
I hope the REST awareness in order to support other backoffices like `marmelab/admin-ng` will be in 1.3 stack? 
Well we'll see :)

**Pull request merged**
