### PR TITLE
Fixes #735: Replace deprecated annotations:

### LINKED ISSUE #735: Is the @PHPCR\String() annotation deprecated?
On http://symfony.com/doc/master/cmf/book/database_layer.html#add-mapping-information, we can see this code:

    class Task
    {
        /...

        /**
         * @PHPCR\String()
         */
        protected $description;

Isn't the `@PHPCR\String()` annotation deprecated? See https://github.com/doctrine/mongodb-odm/issues/1168 or https://github.com/doctrine/phpcr-odm/issues/678 for examples.

I can submit a PR with the annotations if you want.

### PR DESCRIPTION
**Pull request by alexislefebvre**
@PHPCR\String() → @PHPCR\Field(type="string")
    @PHPCR\Boolean() → @PHPCR\Field(type="boolean")

### CODE REVIEW

**Comment by alexislefebvre** [comment]
While working on #735, I found some other files with the deprecated annotations, they are included here.

**Comment by dbu** [comment]
thanks a lot!

ups, now i just wonder: we do explain that this is only from version 1.3 on and that its because of php7?

**Comment by alexislefebvre** [comment]
@dbu I presume this documentation is for new users, I don't think it's relevant to mention that it's new in 1.3 or that it's related to PHP7 as long as it works.

**Comment by dbu** [comment]
its ok here. and its well explained at http://docs.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/reference/annotations-mapping.html#mapping-fields which is the important location.

**Pull request merged**
