### PR TITLE
MainBundle by DemoBundle

### PR DESCRIPTION
**Pull request by Snowbaha**
I Am doing the tuto and the right name is "Demo" and not "Main"

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1: Will merge this soon into 1.1

**Comment by ousmaneNdiaye** [comment]
:+1:

**Comment by dbu** [comment]
thanks a lot!
manually merged into the 1.2 branch.

**Comment by ousmaneNdiaye** [comment]
:clap: @Snowbaha  :clap:

**Pull request closed without merging**
