### PR TITLE
Suggested use of Testing component in contributing section

### PR DESCRIPTION
**Pull request by eiannone**

### CODE REVIEW

**Comment by eiannone** [comment]
I wasn't sure about what branch submit the changes to, so I chose the oldest maintained one, according to [Symfony guidelines](http://symfony.com/doc/current/contributing/documentation/overview.html)

**Comment by dbu** [comment]
there is also documentation about the testing component in the documentation itself. i am not sure if we need to re-state this here - all bundles already use the component and afaik the symfony contribution guidelines themself specify that one should test.

@WouterJ what do you think?

**Comment by dbu** [comment]
ping @WouterJ

**Comment by WouterJ** [comment]
I agree with @dbu here. I also don't think that using the Testing component is a requirement/standard, it's just usefull to use it :)

**Pull request closed without merging**
