### PR TITLE
Changed some of the commands

### PR DESCRIPTION
**Pull request by bogdaniel**
Some of the commands were app/console instead of bin\console

### CODE REVIEW

**Comment by dbu** [comment]
thanks for this fix. the path indeed changed to bin/console. can you please change to the forward slash, for consistency? the backslash is windows shell, while linux/osx/cygwin/bash on windows use forward slash.

**Comment by dbu** [comment]
ping @bogdaniel

**Comment by bogdaniel** [comment]
sorry i will change it.

**Comment by dbu** [comment]
thanks a lot!

**Comment by bogdaniel** [comment]
no problem .. i will try to make more requests where i find something that needs changed .. :D i kinda stay a while before i finally managed getting the tutorial done cuz of different problems :D

**Pull request merged**
